"""Encrypted SQLAlchemy column helpers for sensitive string fields."""

from typing import Any

from cryptography.fernet import Fernet, InvalidToken
from sqlalchemy import Text
from sqlalchemy.types import TypeDecorator

from app.core.config import get_settings


class EncryptionConfigurationError(RuntimeError):
    """Raised when field encryption cannot be configured."""


def _get_fernet() -> Fernet:
    """Build a Fernet instance from application settings.

    Returns:
        Fernet: Configured Fernet encryptor/decryptor.

    Raises:
        EncryptionConfigurationError: If SECRET_KEY is empty or is not a Fernet key.
    """

    secret_key = get_settings().secret_key.get_secret_value()
    if not secret_key:
        msg = "SECRET_KEY must be set to a valid Fernet key for encrypted fields."
        raise EncryptionConfigurationError(msg)
    try:
        return Fernet(secret_key.encode("utf-8"))
    except ValueError as exc:
        msg = "SECRET_KEY must be a valid Fernet key generated by Fernet.generate_key()."
        raise EncryptionConfigurationError(msg) from exc


def encrypt_field(value: str) -> str:
    """Encrypt a plaintext string for storage.

    Args:
        value: Plaintext value to encrypt.

    Returns:
        str: Fernet token encoded as text.
    """

    return _get_fernet().encrypt(value.encode("utf-8")).decode("utf-8")


def decrypt_field(value: str) -> str:
    """Decrypt a stored Fernet token.

    Args:
        value: Fernet token encoded as text.

    Returns:
        str: Decrypted plaintext.

    Raises:
        EncryptionConfigurationError: If the stored value cannot be decrypted.
    """

    try:
        return _get_fernet().decrypt(value.encode("utf-8")).decode("utf-8")
    except InvalidToken as exc:
        msg = "Encrypted field value could not be decrypted with the configured SECRET_KEY."
        raise EncryptionConfigurationError(msg) from exc


class EncryptedString(TypeDecorator[str]):
    """SQLAlchemy type that transparently encrypts and decrypts strings."""

    impl = Text
    cache_ok = True

    def process_bind_param(self, value: str | None, dialect: Any) -> str | None:
        """Encrypt values before binding them to SQL statements."""

        if value is None:
            return None
        return encrypt_field(value)

    def process_result_value(self, value: str | None, dialect: Any) -> str | None:
        """Decrypt values loaded from SQL result rows."""

        if value is None:
            return None
        return decrypt_field(value)
