[mypy]
python_version = 3.11
mypy_path = .
strict = true
plugins = pydantic.mypy
warn_unused_configs = true
warn_unreachable = true
show_error_codes = true
pretty = true
exclude = ^(tests/|alembic/|scripts/)
