"""Markdown builders for GitLab review feedback."""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Sequence
from uuid import UUID

from app.engines import Finding


def build_review_summary_note(
    *,
    review_id: UUID,
    findings: Sequence[Finding],
    has_blocker: bool,
    blocker_count: int,
    policy_applied: str | None,
    detail_url: str | None,
    engine_error: str | None = None,
    review_mode: str | None = None,
    incremental_base_sha: str | None = None,
    incremental_head_sha: str | None = None,
    new_finding_count: int | None = None,
    carried_finding_count: int | None = None,
    mode_reason: str | None = None,
    new_findings: Sequence[Finding] | None = None,
    carried_findings: Sequence[Finding] | None = None,
) -> str:
    """Render the top-level GitLab MR summary note for one review run.

    引擎失败时（``engine_error`` 非空）**顶部横幅**改成醒目的 ``# ⚠️ AI Review
    FAILED`` 标题 + 一条一句话说明，避免把 "PASSED / 0 findings" 装作正常
    完成——那是我们在
    `fix/main-llm-fail-error-and-config` 之前踩到的坑。

    增量审查引入后新增可选参数：
      - ``review_mode``: ``"full"`` / ``"incremental"`` / ``"reuse"``；
      - ``incremental_base_sha`` / ``incremental_head_sha``: 增量模式下用于
        在顶部提示 ``prev_head → new_head``；
      - ``new_finding_count`` / ``carried_finding_count``: 增量模式下分别是
        本次新增与历史遗留数量；
      - ``mode_reason``: 供 rebase 降级等场景在顶部加一句解释（如
        ``history_rewritten``）。

    v2 汇总（本次 PR）新增两组可选 findings 集合参数：
      - ``new_findings``: 本次 push 新引入的 findings（增量模式下由
        orchestrator 从 ``merge.new_findings`` 传入）；
      - ``carried_findings``: 未改动文件里遗留的历史 findings（对应
        ``merge.carried_over_untouched``）。

    传入这两组参数后，Findings 段落会拆分成两个二级标题：``🆕 本次新增`` 与
    ``📌 历史遗留``，并在每个分区内按 ``file_path`` 分组、按 severity 排序。
    两者都未传时保持向后兼容——所有 findings 都当作"新增"分区展示，等价于
    旧扁平列表的分组升级版。

    这些字段全部可选，老调用点不传时行为完全等价旧输出。
    """

    if engine_error is not None:
        lines = [
            "# ⚠️ AI Review FAILED",
            "",
            "**本次 AI 审查未能完成，请人工审查这次 MR。**",
            "",
            f"- Review ID: `{review_id}`",
            f"- Result: {'BLOCKED' if has_blocker else 'FAILED (policy allowed merge)'}",
            "- Findings: 0 (engine did not run)",
            f"- Blocking findings: {blocker_count} blocking finding(s)",
        ]
        if policy_applied:
            lines.append(f"- Policy: `{policy_applied}`")
        if detail_url:
            lines.append(f"- Details: {detail_url}")
        if review_mode == "full" and mode_reason == "history_rewritten":
            # 引擎失败时也把 rebase 降级信息带出来，避免用户以为审查是老范围。
            lines.append("- ⚠️ 检测到 history 被改写，本次改为全量重审")
        lines.extend(
            [
                "",
                "### Engine error",
                "",
                engine_error,
                "",
                "_Generated by ai-code-reviewer._",
            ]
        )
        return "\n".join(lines)

    output: list[str] = []
    # 模式横幅：非默认 full 或者带 rebase 降级原因时才展示，减少信息噪声。
    banner = _build_mode_banner(
        review_mode=review_mode,
        incremental_base_sha=incremental_base_sha,
        incremental_head_sha=incremental_head_sha,
        new_finding_count=new_finding_count,
        carried_finding_count=carried_finding_count,
        mode_reason=mode_reason,
        total=len(findings),
    )
    if banner:
        output.extend([banner, ""])
    output.extend(
        [
            "## AI Review completed",
            "",
            f"- Review ID: `{review_id}`",
            f"- Result: {'BLOCKED' if has_blocker else 'PASSED'}",
            f"- Findings: {len(findings)} finding(s)",
            f"- Blocking findings: {blocker_count} blocking finding(s)",
        ]
    )
    if policy_applied:
        output.append(f"- Policy: `{policy_applied}`")
    if detail_url:
        output.append(f"- Details: {detail_url}")

    # v2 分区：优先看调用方是否提供了 new/carried；都没提供则视为向后兼容，
    # 把 findings 全部当新增分区展示。
    provided_split = new_findings is not None or carried_findings is not None
    if provided_split:
        new_list = list(new_findings or [])
        carried_list = list(carried_findings or [])
    else:
        new_list = list(findings)
        carried_list = []

    if not new_list and not carried_list:
        output.extend(["", "No findings were reported by the configured engine."])
    else:
        if new_list:
            output.extend(
                [
                    "",
                    f"### 🆕 本次新增（{len(new_list)} 条）",
                    "",
                ]
            )
            output.extend(_render_findings_section(new_list))
        if carried_list:
            output.extend(
                [
                    "",
                    f"### 📌 历史遗留（未改动文件，{len(carried_list)} 条）",
                    "",
                    "> 以下问题所在文件本次 push 未改动，保留自上一次审查。",
                    "",
                ]
            )
            output.extend(_render_findings_section(carried_list))
    output.extend(["", "_Generated by ai-code-reviewer._"])
    return "\n".join(output)


def build_finding_discussion_body(finding: Finding) -> str:
    """Render one line-level GitLab discussion body for a finding."""

    lines = [f"**[{finding.severity}] {finding.title}**"]
    if finding.description:
        lines.extend(["", finding.description])
    if finding.suggestion:
        lines.extend(["", f"Suggestion: {finding.suggestion}"])
    return "\n".join(lines)


# severity → 权重。同时兼容大小写与规范里提到的 blocker/critical/high/medium/low/info
# 命名；未识别的字符串一律视作 0，避免顺序抖动。
_SEVERITY_WEIGHTS: dict[str, int] = {
    "blocker": 4,
    "critical": 3,
    "high": 3,
    "warning": 2,
    "medium": 2,
    "low": 1,
    "info": 0,
}


def _severity_weight(severity: str | None) -> int:
    """归一化后查权重表。未知或 None 返回 0。"""

    if severity is None:
        return 0
    return _SEVERITY_WEIGHTS.get(severity.lower(), 0)


def _render_findings_section(findings: Sequence[Finding]) -> list[str]:
    """把一组 findings 按 ``file_path`` 分组、渲染为 markdown 行。

    文件排序：先按"文件内最高 severity 权重"降序，再按 finding 数量降序，
    最后按 file_path 字母序稳定兜底。文件内部按 ``line_number ASC``
    （``None`` 排到最后），再按 severity 权重降序。
    """

    grouped: dict[str, list[Finding]] = defaultdict(list)
    for finding in findings:
        grouped[finding.file_path].append(finding)

    def _file_sort_key(item: tuple[str, list[Finding]]) -> tuple[int, int, str]:
        path, items = item
        max_weight = max((_severity_weight(f.severity) for f in items), default=0)
        # 负号让"越严重/越多"排前面；file_path 用字符串正向做字母序 tiebreak。
        return (-max_weight, -len(items), path)

    lines: list[str] = []
    for file_path, file_findings in sorted(grouped.items(), key=_file_sort_key):
        ordered = sorted(
            file_findings,
            key=lambda f: (
                # None 排最后：用 (has_line=0/1, line) 组合，None 变 (1, 0)。
                (0, f.line_number) if f.line_number is not None else (1, 0),
                -_severity_weight(f.severity),
            ),
        )
        lines.extend(
            [
                f"#### `{file_path}` （{len(ordered)} 条）",
                "",
            ]
        )
        for finding in ordered:
            severity_label = finding.severity.upper()
            lines.append(f"- **[{severity_label}] {finding.title}**")
            if finding.line_number is not None:
                # 保留 file:line 完整定位——分组标题只有文件名，遗漏行号会让
                # 用户在长文件里找不着；同时兼容旧断言 ``file.py:LINE``。
                lines.append(f"  - Location: `{finding.file_path}:{finding.line_number}`")
            lines.append(f"  - Rule: `{finding.rule_id}`")
            if finding.description:
                lines.append(f"  - Description: {finding.description}")
            if finding.suggestion:
                lines.append(f"  - Suggestion: {finding.suggestion}")
        lines.append("")
    return lines


def _build_mode_banner(
    *,
    review_mode: str | None,
    incremental_base_sha: str | None,
    incremental_head_sha: str | None,
    new_finding_count: int | None,
    carried_finding_count: int | None,
    mode_reason: str | None,
    total: int,
) -> str | None:
    """构造顶部一行模式横幅。返回 None 表示不展示（默认 full 模式）。

    incremental 模式：``ℹ️ 本次为增量审查（<base[:7]> → <head[:7]>），共 X 条
    （本次新增 A / 历史遗留 B）``
    reuse 模式：``ℹ️ CI 重跑，复用上一次审查结果``
    full + history_rewritten：``⚠️ 检测到 history 被改写，本次改为全量重审``
    """

    if review_mode == "incremental":
        base_short = (incremental_base_sha or "?")[:7]
        head_short = (incremental_head_sha or "?")[:7]
        parts = [
            "ℹ️ 本次为增量审查",
            f"（相较上一次 push 的 {base_short} → {head_short}）",
            f"，共 {total} 条问题",
        ]
        if new_finding_count is not None and carried_finding_count is not None:
            parts.append(
                f"（本次新增 {new_finding_count} / 历史遗留 {carried_finding_count}）",
            )
        return "".join(parts)
    if review_mode == "reuse":
        return "ℹ️ CI 重跑，复用上一次审查结果"
    if review_mode == "full" and mode_reason == "history_rewritten":
        return "⚠️ 检测到 history 被改写，本次改为全量重审"
    return None
