"""Markdown builders for GitLab review feedback."""

from __future__ import annotations

from collections.abc import Sequence
from uuid import UUID

from app.engines import Finding


def build_review_summary_note(
    *,
    review_id: UUID,
    findings: Sequence[Finding],
    has_blocker: bool,
    blocker_count: int,
    policy_applied: str | None,
    detail_url: str | None,
    engine_error: str | None = None,
) -> str:
    """Render the top-level GitLab MR summary note for one review run."""

    lines = [
        "## AI Review completed",
        "",
        f"- Review ID: `{review_id}`",
        f"- Result: {'BLOCKED' if has_blocker else 'PASSED'}",
        f"- Findings: {len(findings)} finding(s)",
        f"- Blocking findings: {blocker_count} blocking finding(s)",
    ]
    if policy_applied:
        lines.append(f"- Policy: `{policy_applied}`")
    if detail_url:
        lines.append(f"- Details: {detail_url}")
    if engine_error:
        lines.extend(["", "### Engine error", "", engine_error])
    if not findings:
        lines.extend(["", "No findings were reported by the configured engine."])
    else:
        lines.extend(["", "### Findings", ""])
        for index, finding in enumerate(findings, start=1):
            location = _format_location(finding)
            lines.extend(
                [
                    f"{index}. **[{finding.severity}] {finding.title}**",
                    f"   - Location: `{location}`",
                    f"   - Rule: `{finding.rule_id}`",
                ]
            )
            if finding.description:
                lines.append(f"   - Description: {finding.description}")
            if finding.suggestion:
                lines.append(f"   - Suggestion: {finding.suggestion}")
            lines.append("")
    lines.extend(["", "_Generated by ai-code-reviewer._"])
    return "\n".join(lines)


def build_finding_discussion_body(finding: Finding) -> str:
    """Render one line-level GitLab discussion body for a finding."""

    lines = [f"**[{finding.severity}] {finding.title}**"]
    if finding.description:
        lines.extend(["", finding.description])
    if finding.suggestion:
        lines.extend(["", f"Suggestion: {finding.suggestion}"])
    return "\n".join(lines)


def _format_location(finding: Finding) -> str:
    """Format a finding location for Markdown output."""

    if finding.line_number is None:
        return finding.file_path
    return f"{finding.file_path}:{finding.line_number}"
