"""Markdown builders for GitLab review feedback."""

from __future__ import annotations

from collections.abc import Sequence
from uuid import UUID

from app.engines import Finding


def build_review_summary_note(
    *,
    review_id: UUID,
    findings: Sequence[Finding],
    has_blocker: bool,
    blocker_count: int,
    policy_applied: str | None,
    detail_url: str | None,
    engine_error: str | None = None,
    review_mode: str | None = None,
    incremental_base_sha: str | None = None,
    incremental_head_sha: str | None = None,
    new_finding_count: int | None = None,
    carried_finding_count: int | None = None,
    mode_reason: str | None = None,
) -> str:
    """Render the top-level GitLab MR summary note for one review run.

    引擎失败时（``engine_error`` 非空）**顶部横幅**改成醒目的 ``# ⚠️ AI Review
    FAILED`` 标题 + 一条一句话说明，避免把 "PASSED / 0 findings" 装作正常
    完成——那是我们在
    `fix/main-llm-fail-error-and-config` 之前踩到的坑。

    增量审查引入后新增可选参数：
      - ``review_mode``: ``"full"`` / ``"incremental"`` / ``"reuse"``；
      - ``incremental_base_sha`` / ``incremental_head_sha``: 增量模式下用于
        在顶部提示 ``prev_head → new_head``；
      - ``new_finding_count`` / ``carried_finding_count``: 增量模式下分别是
        本次新增与历史遗留数量；
      - ``mode_reason``: 供 rebase 降级等场景在顶部加一句解释（如
        ``history_rewritten``）。

    这些字段全部可选，老调用点不传时行为完全等价旧输出。
    """

    if engine_error is not None:
        lines = [
            "# ⚠️ AI Review FAILED",
            "",
            "**本次 AI 审查未能完成，请人工审查这次 MR。**",
            "",
            f"- Review ID: `{review_id}`",
            f"- Result: {'BLOCKED' if has_blocker else 'FAILED (policy allowed merge)'}",
            "- Findings: 0 (engine did not run)",
            f"- Blocking findings: {blocker_count} blocking finding(s)",
        ]
        if policy_applied:
            lines.append(f"- Policy: `{policy_applied}`")
        if detail_url:
            lines.append(f"- Details: {detail_url}")
        if review_mode == "full" and mode_reason == "history_rewritten":
            # 引擎失败时也把 rebase 降级信息带出来，避免用户以为审查是老范围。
            lines.append("- ⚠️ 检测到 history 被改写，本次改为全量重审")
        lines.extend(
            [
                "",
                "### Engine error",
                "",
                engine_error,
                "",
                "_Generated by ai-code-reviewer._",
            ]
        )
        return "\n".join(lines)

    output: list[str] = []
    # 模式横幅：非默认 full 或者带 rebase 降级原因时才展示，减少信息噪声。
    banner = _build_mode_banner(
        review_mode=review_mode,
        incremental_base_sha=incremental_base_sha,
        incremental_head_sha=incremental_head_sha,
        new_finding_count=new_finding_count,
        carried_finding_count=carried_finding_count,
        mode_reason=mode_reason,
        total=len(findings),
    )
    if banner:
        output.extend([banner, ""])
    output.extend(
        [
            "## AI Review completed",
            "",
            f"- Review ID: `{review_id}`",
            f"- Result: {'BLOCKED' if has_blocker else 'PASSED'}",
            f"- Findings: {len(findings)} finding(s)",
            f"- Blocking findings: {blocker_count} blocking finding(s)",
        ]
    )
    if policy_applied:
        output.append(f"- Policy: `{policy_applied}`")
    if detail_url:
        output.append(f"- Details: {detail_url}")
    if not findings:
        output.extend(["", "No findings were reported by the configured engine."])
    else:
        output.extend(["", "### Findings", ""])
        for index, finding in enumerate(findings, start=1):
            location = _format_location(finding)
            output.extend(
                [
                    f"{index}. **[{finding.severity}] {finding.title}**",
                    f"   - Location: `{location}`",
                    f"   - Rule: `{finding.rule_id}`",
                ]
            )
            if finding.description:
                output.append(f"   - Description: {finding.description}")
            if finding.suggestion:
                output.append(f"   - Suggestion: {finding.suggestion}")
            output.append("")
    output.extend(["", "_Generated by ai-code-reviewer._"])
    return "\n".join(output)


def build_finding_discussion_body(finding: Finding) -> str:
    """Render one line-level GitLab discussion body for a finding."""

    lines = [f"**[{finding.severity}] {finding.title}**"]
    if finding.description:
        lines.extend(["", finding.description])
    if finding.suggestion:
        lines.extend(["", f"Suggestion: {finding.suggestion}"])
    return "\n".join(lines)


def _format_location(finding: Finding) -> str:
    """Format a finding location for Markdown output."""

    if finding.line_number is None:
        return finding.file_path
    return f"{finding.file_path}:{finding.line_number}"


def _build_mode_banner(
    *,
    review_mode: str | None,
    incremental_base_sha: str | None,
    incremental_head_sha: str | None,
    new_finding_count: int | None,
    carried_finding_count: int | None,
    mode_reason: str | None,
    total: int,
) -> str | None:
    """构造顶部一行模式横幅。返回 None 表示不展示（默认 full 模式）。

    incremental 模式：``ℹ️ 本次为增量审查（<base[:7]> → <head[:7]>），共 X 条
    （本次新增 A / 历史遗留 B）``
    reuse 模式：``ℹ️ CI 重跑，复用上一次审查结果``
    full + history_rewritten：``⚠️ 检测到 history 被改写，本次改为全量重审``
    """

    if review_mode == "incremental":
        base_short = (incremental_base_sha or "?")[:7]
        head_short = (incremental_head_sha or "?")[:7]
        parts = [
            "ℹ️ 本次为增量审查",
            f"（相较上一次 push 的 {base_short} → {head_short}）",
            f"，共 {total} 条问题",
        ]
        if new_finding_count is not None and carried_finding_count is not None:
            parts.append(
                f"（本次新增 {new_finding_count} / 历史遗留 {carried_finding_count}）",
            )
        return "".join(parts)
    if review_mode == "reuse":
        return "ℹ️ CI 重跑，复用上一次审查结果"
    if review_mode == "full" and mode_reason == "history_rewritten":
        return "⚠️ 检测到 history 被改写，本次改为全量重审"
    return None
